services:
  gpumon:
    build: .
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /tmp:/tmp
    env_file:
      - path: .env
        required: false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
